# Generated by Django 6.0.1 on 2026-01-14 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=50)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('smartcredit_config', models.JSONField(blank=True, default=dict)),
                ('lob_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('ssn_encrypted', models.BinaryField(blank=True, null=True)),
                ('ssn_last4', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('addresses', models.JSONField(default=list)),
                ('phones', models.JSONField(default=list)),
                ('emails', models.JSONField(default=list)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consumers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='customers.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartCreditConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.BinaryField()),
                ('refresh_token', models.BinaryField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=20)),
                ('sc_user_id', models.CharField(blank=True, max_length=100)),
                ('sc_subscription_id', models.CharField(blank=True, max_length=100)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('pull_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartcredit_connections', to='customers.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('bureau', models.CharField(choices=[('equifax', 'Equifax'), ('experian', 'Experian'), ('transunion', 'TransUnion')], max_length=20)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('raw_json', models.JSONField()),
                ('raw_json_hash', models.CharField(max_length=64)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('score_factors', models.JSONField(default=list)),
                ('tradeline_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('public_record_count', models.PositiveIntegerField(default=0)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parse_errors', models.JSONField(default=list)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_reports', to='customers.consumer')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.smartcreditconnection')),
            ],
            options={
                'ordering': ['-pulled_at'],
            },
        ),
        migrations.CreateModel(
            name='Tradeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bureau', models.CharField(choices=[('equifax', 'Equifax'), ('experian', 'Experian'), ('transunion', 'TransUnion')], max_length=20)),
                ('bureau_item_id', models.CharField(blank=True, max_length=100)),
                ('creditor_name', models.CharField(max_length=255)),
                ('creditor_address', models.JSONField(blank=True, default=dict)),
                ('account_number_masked', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('original_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('past_due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account_status', models.CharField(blank=True, max_length=50)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('payment_history', models.JSONField(default=dict)),
                ('dispute_status', models.CharField(choices=[('none', 'No Dispute'), ('in_dispute', 'In Dispute'), ('resolved', 'Resolved'), ('verified', 'Verified as Accurate')], default='none', max_length=20)),
                ('has_consumer_statement', models.BooleanField(default=False)),
                ('remarks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradelines', to='customers.consumer')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradelines', to='customers.creditreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smartcreditconnection',
            index=models.Index(fields=['consumer', 'status'], name='customers_s_consume_0c9985_idx'),
        ),
        migrations.AddIndex(
            model_name='creditreport',
            index=models.Index(fields=['consumer', 'bureau'], name='customers_c_consume_878861_idx'),
        ),
        migrations.AddIndex(
            model_name='creditreport',
            index=models.Index(fields=['consumer', 'pulled_at'], name='customers_c_consume_9cb358_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['tenant', 'ssn_last4'], name='customers_c_tenant__4fa3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='customers_c_tenant__47a206_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['tenant', 'kyc_status'], name='customers_c_tenant__d12289_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeline',
            index=models.Index(fields=['consumer', 'bureau'], name='customers_t_consume_535132_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeline',
            index=models.Index(fields=['consumer', 'creditor_name'], name='customers_t_consume_0b87c8_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeline',
            index=models.Index(fields=['consumer', 'dispute_status'], name='customers_t_consume_b1e5e3_idx'),
        ),
    ]
